#!/bin/bash
#trap : SIGTERM SIGINT

# TODO end this
if [ -n "$1" ] ; then
  if [ "$1" -ge "$index_begining" ] ; then
    stream_number="$1"
  else
    stream_number="$index_begining"
  fi
else
  stream_number="$index_begining"
fi

# TODO what if undefined ?
config_file=$XDG_CONFIG_HOME/streamplayer/conf
# TODO what if undefined ?
pid_file=$XDG_RUNTIME_DIR/streamplayer.pid
# TODO $player must contain no whitespace to compare with /proc/.../cmdline
player=mplayer

if [ -e $pid_file ]
then
  echo "$pid_file"
  kill `cat /run/user/$UID/streamplayer.pid`
else
  while read -r line
  do
    IFS=' ' read stream_name stream_url <<< "$line"
    echo "$stream_name"
    $player "$stream_url" >/dev/null 2>/dev/null &
    player_pid="$!"
    echo "$player_pid" > "$pid_file"

    wait
    echo 'next'
    rm "$pid_file"
  done < "$config_file"
fi
