#!/bin/bash
#trap : SIGTERM SIGINT

# TODO take a radio numer in agrument, default behavior if -1

# TODO what if undefined ?
config_file=$XDG_CONFIG_HOME/streamplayer/conf
# TODO what if undefined ?
pid_file=$XDG_RUNTIME_DIR/streamplayer.pid
# TODO $player must contain no whitespace to compare with /proc/.../cmdline
player=mplayer

if [ -e $pid_file ]
then
  kill `cat $pid_file`
else
  while read -r line
  do
    IFS=' ' read stream_name stream_url <<< $line
    echo $stream_name
    $player $stream_url >/dev/null 2>/dev/null &
    player_pid=$!
    echo $player_pid > $pid_file

    wait
    echo 'next'
    rm $pid_file
  done <<< `cat "$config_file"`
  exit 0
fi
